In [2]:
!ls /home/bitai/proj_my/Applied-Deep-Learning-with-Keras

Lesson01  Lesson03  Lesson05  Lesson07	Lesson09  README.md
Lesson02  Lesson04  Lesson06  Lesson08	LICENSE


In [3]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [ ]:
# sudo apt-get install pkg-config
# pkg-config --modversion opencv
# opencv에서 설치 안됐다고 뱉으면 다음으로 넘어가기
# (나오면 삭제해야해서 오히려 골치아픔)

# sudo apt-get install build-essential cmake
# sudo apt-get install freeglut3 freeglut3-dev
# sudo apt-get install glew-utils glee-dev
# sudo apt-get install libglew-dev
# sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev
# sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev libx264-dev libxine2-dev
# sudo apt-get install libv4l-dev v4l-utils
# sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
# sudo apt-get install libgtk2.0-dev
# sudo apt-get install mesa-utils libgl1-mesa-dri libgtkgl2.0-dev libgtkglext1-dev
# sudo apt-get install libatlas-base-dev gfortran libeigen3-dev

In [ ]:
# cd ~
# cd sw/
# mkdir opencv
# cd opencv
# wget -O opencv.zip https://github.com/opencv/opencv/archive/4.2.0.zip
# unzip opencv.zip

In [ ]:
# wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.2.0.zip
# unzip opencv_contrib.zip

In [ ]:
# cd opencv-4.2.0/
# mkdir build
# cd build

In [ ]:
# 아나콘다 환경 설정 잠시 정지시킴
# sudo apt-get install python2.7-dev python3-dev python-numpy python3-numpy

In [ ]:
# /home/bitai/anaconda3/bin/python

In [ ]:
# 아나콘다 경로를 잘 파악하고 있다면 문제 없음
# cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=OFF -D WITH_IPP=OFF -D WITH_1394=OFF -D BUILD_WITH_DEBUG_INFO=OFF -D BUILD_DOCS=OFF -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D WITH_QT=OFF -D WITH_GTK=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.2.0/modules -D WITH_V4L=ON -D WITH_FFMPEG=ON -D WITH_XINE=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D OPENCV_GENERATE_PKGCONFIG=ON ../

In [ ]:
# 아나콘다상의 파이썬 경로를 파악하지 못한다면 아래 방식으로
# cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=OFF -D WITH_IPP=OFF -D WITH_1394=OFF -D BUILD_WITH_DEBUG_INFO=OFF -D BUILD_DOCS=OFF -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D WITH_QT=OFF -D WITH_GTK=ON -D WITH_OPENGL=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.2.0/modules -D WITH_V4L=ON -D WITH_FFMPEG=ON -D WITH_XINE=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D OPENCV_GENERATE_PKGCONFIG=ON -D PYTHON3_INCLUDE_DIR=/home/bitai/anaconda3/include/python3.7m/ -D PYTHON3_NUMPY_INCLUDE_DIRS=/home/bitai/anaconda3/lib/python3.7/site-packages/numpy/core/include/ -D PYTHON3_PACKAGES_PATH=/home/bitai/anaconda3/lib/python3.7/site-packages -D PYTHON3_LIBRARY=/home/bitai/anaconda3/lib/libpython3.7m.so ../

In [ ]:
# cat /proc/cpuinfo | grep processor | wc -l
# time make -j12

In [ ]:
# sudo make install

In [ ]:
# cat /etc/ld.so.conf.d/*
# sudo ldconfig

In [ ]:
# cd ~/proj/
# mkdir test
# cd test
# g++ -o facedetect /usr/local/share/opencv4/samples/cpp/facedetect.cpp $(pkg-config opencv4 --libs --cflags)
# ./facedetect --cascade="/usr/local/share/opencv4/haarcascades/haarcascade_frontalface_alt.xml" --nested-cascade="/usr/local/share/opencv4/haarcascades/haarcascade_eye_tree_eyeglasses.xml" --scale=1.3

In [ ]:
# 아나콘다 설정 다시 활성화

In [ ]:
# !pip install opencv-python
# 위는 주피터에서 쓰는 코드고 터미널에서 이미 완료함

In [1]:
import cv2

In [2]:
print(cv2.__version__)

4.3.0


In [3]:
import numpy as np

In [4]:
img = np.random.randint(0, 10, (7, 7))

print(img)

[[7 5 9 3 1 5 0]
 [5 9 7 0 8 9 8]
 [7 4 8 6 1 7 3]
 [2 3 4 8 0 0 6]
 [8 7 3 2 5 1 0]
 [2 6 1 3 9 9 6]
 [9 2 3 0 7 0 8]]


In [5]:
img_np = np.ones([7, 7])

print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [6]:
kernel = np.array([-1, 0, 1])

print(kernel)

[-1  0  1]


In [7]:
# 넘파이 형식으로 이미지에는 못씀, 변환필요
print(type(kernel))
print(type(img_np))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
img_cv = cv2.resize(img_np, (7, 7))

print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [9]:
kernel = cv2.resize(kernel, (1, 3))

print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [10]:
# 넘피로 나오지만 이미지 연산에 쓸 수 있음
print(type(img_cv))
print(type(kernel))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [12]:
print(kernel)

[[-1]
 [ 0]
 [ 1]]


In [13]:
print(img_cv)

# 가로는 0
# 세로는 ??

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [14]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3

# filter2D - Convolution이
# 결국 라플라스 변환과 푸리에 변환에 관계를 가지고 있기 때문
conv_test = cv2.filter2D(img_cv, -1, kernel)

print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [15]:
# sudo apt-get install ctags cscope

# in, k(kernel)가 중요

In [16]:
# 책 끝나고 아래 내용 다시 설명해주기로 함
# 까먹으면 말해달라고 하심

# 라플라스 변환 => 전달 함수를 얻기 위해 계산함
# 라플라스 변환 - 미분 쉽게 계산하려고 배움?(거짓말)
# 입력 대 출력비를 구하겠다.
# 입력이 10, 출력이 7, 입출력비: 7/10
# 입력이 y'' = y' + 3y + 2
# 출력이 y' = 3e^3x => y = e^3x
# 라플라스 변환 통해 입출력비를 계산할 수 있게 된다. 
# 미분 방정식으로도 구할 수 없는 출력비를 구할 때 라플라스를 쓴다.

# 라플라스 역변환하면 시간의 함수가 얻어짐(원래값 x(t)?)
# integral 0 ~ inf(무한) f(t)e^-st dt 
# 퀄컴 s-시프팅, 스마트폰에 이미 있음? 

# 1계 미분 방정식(RC 회로)
# 라플라스 변환, 푸리에 변환 약식
# Low Pass Filter(LPF 설계법) - 1D Convolution
# 전달함수 -> 실제 값을 필터링 하는 방법

In [17]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [18]:
classifier = Sequential()
classifier.add(
    Conv2D(
        32, (3, 3), 
        input_shape = (64, 64, 3), 
        activation = 'relu'
    )
)
classifier.add(
    Conv2D(
        32, (3, 3), 
        activation = 'relu'
    )
)
classifier.add(
    Conv2D(
        32, (3, 3), 
        activation = 'relu'
    )
)


# MaxPool2D 2 by 2 행렬로 이동하면서 최대 풀링을 해준다? 
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(Flatten())

In [19]:
# 컨볼루션 할 네트워크 확인
# 텐서 연산을 사용하고 있다 / (None, 62, 62, 32) 
classifier.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 32)        896       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 60, 60, 32)        9248      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 58, 58, 32)        9248      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 29, 29, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 6272)              0         
Total params: 19,392
Trainable params: 19,392
Non-trainable params: 0
____________________________________________________

In [65]:
# 네트워크 모델 1 - 50%, 오판

classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(1, activation = 'softmax')
)

classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [76]:
# 네트워크 모델 2 - 50% 대

classifier.add(
    Dense(512, activation = 'tanh')
)
classifier.add(
    Dense(300, activation = 'tanh')
)
classifier.add(
    Dense(150, activation = 'tanh')
)
classifier.add(
    Dense(75, activation = 'tanh')
)

classifier.add(
    Dense(300, activation = 'tanh')
)

classifier.add(
    Dense(1, activation = 'sigmoid')
)

classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [78]:
# 네트워크 모델 3

classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(64, activation = 'relu')
)
classifier.add(
    Dense(32, activation = 'relu')
)
classifier.add(
    Dense(16, activation = 'relu')
)
classifier.add(
    Dense(1, activation = 'sigmoid')
)

classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [66]:
from keras.preprocessing.image import ImageDataGenerator

train_gen = ImageDataGenerator(
    # 0~255의 값을 0~1.0으로 수렴 시킨다? 
    rescale = 1.0 / 255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True
)

test_gen = ImageDataGenerator(rescale = 1.0 / 255)
# train_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [36]:
!ls /home/bitai/proj_my/Applied-Deep-Learning-with-Keras

Lesson01  Lesson03  Lesson05  Lesson07	Lesson09  README.md
Lesson02  Lesson04  Lesson06  Lesson08	LICENSE


In [37]:
!ls /home/bitai/proj_my/Applied-Deep-Learning-with-Keras/Lesson07/

Activity13.ipynb  Datasets	    Exercise20.ipynb  Exercise22.ipynb
Activity14.ipynb  Exercise19.ipynb  Exercise21.ipynb


In [38]:
!ls /home/bitai/proj_my/Applied-Deep-Learning-with-Keras/Lesson07/Datasets/

 dataset  'test images'


In [39]:
!ls /home/bitai/proj_my/Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/

test_set  training_set


In [40]:
!ls /home/bitai/proj_my/Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set/

cats  dogs


In [22]:
trainSet = train_gen.flow_from_directory(
    '/home/bitai/proj_my/Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set/',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)
testSet = test_gen.flow_from_directory(
    '/home/bitai/proj_my/Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/test_set/',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary'
)

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.


In [80]:
batch_size = 50

classifier.fit_generator(
    trainSet,
    steps_per_epoch = int(10000/batch_size),
    epochs = 100,
    validation_data = testSet,
    validation_steps = int(2500/batch_size)
)

# 엘프이프? 미분방정식 알아야 함

Epoch 1/100
200/200 [==============================] - 26s 131ms/step - loss: 0.6932 - accuracy: 0.4936 - val_loss: 0.6931 - val_accuracy: 0.5069
Epoch 2/100
200/200 [==============================] - 26s 130ms/step - loss: 0.6932 - accuracy: 0.4966 - val_loss: 0.6932 - val_accuracy: 0.4812
Epoch 3/100
200/200 [==============================] - 26s 128ms/step - loss: 0.6931 - accuracy: 0.5066 - val_loss: 0.6931 - val_accuracy: 0.5038
Epoch 4/100
200/200 [==============================] - 25s 127ms/step - loss: 0.6932 - accuracy: 0.5052 - val_loss: 0.6930 - val_accuracy: 0.5088
Epoch 5/100
200/200 [==============================] - 26s 128ms/step - loss: 0.6932 - accuracy: 0.4967 - val_loss: 0.6931 - val_accuracy: 0.5163
Epoch 6/100
200/200 [==============================] - 26s 128ms/step - loss: 0.6932 - accuracy: 0.4848 - val_loss: 0.6931 - val_accuracy: 0.5169
Epoch 7/100
200/200 [==============================] - 26s 131ms/step - loss: 0.6932 - accuracy: 0.4973 - val_loss: 0.6932 -

Epoch 57/100
200/200 [==============================] - 25s 127ms/step - loss: 0.6932 - accuracy: 0.4980 - val_loss: 0.6932 - val_accuracy: 0.4994
Epoch 58/100
200/200 [==============================] - 25s 127ms/step - loss: 0.6932 - accuracy: 0.5034 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 59/100
200/200 [==============================] - 26s 129ms/step - loss: 0.6932 - accuracy: 0.4930 - val_loss: 0.6932 - val_accuracy: 0.4800
Epoch 60/100
200/200 [==============================] - 26s 130ms/step - loss: 0.6932 - accuracy: 0.4961 - val_loss: 0.6931 - val_accuracy: 0.5106
Epoch 61/100
200/200 [==============================] - 25s 126ms/step - loss: 0.6931 - accuracy: 0.5041 - val_loss: 0.6932 - val_accuracy: 0.4975
Epoch 62/100
200/200 [==============================] - 26s 128ms/step - loss: 0.6931 - accuracy: 0.5034 - val_loss: 0.6933 - val_accuracy: 0.4869
Epoch 63/100
200/200 [==============================] - 25s 127ms/step - loss: 0.6932 - accuracy: 0.5022 - val_loss: 0

In [ ]:
# 교재는 cpu 베이스의 코드라서 쓸 수가 없음
# gpu 베이스로 코딩을 해야 함

In [32]:
import numpy as np

from keras.preprocessing import image

In [60]:
new_image = image.load_img(
    'test_image_2.jpg',
    target_size = (64, 64)
)

In [61]:
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)

In [75]:
result = classifier.predict(new_image)
# trainSet.class_indices

if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat'
    
print(prediction)

Cat
